In [18]:
import numpy as np

n=3

A1 = [(0,0)]
print(A1)
for i in range(n):
    my_tuple = (i,i)
    A1.append(my_tuple)
print(A1)

A2 = A1.copy()
A3 = A1.copy()

print(A3)




A1_grid, A2_grid, A3_grid= np.meshgrid(A1,A2,A3,indexing='ij')

A_grid = A1_grid + A2_grid + A3_grid

#print(A1_grid)
#print(A2_grid)
#print(A3_grid)
print(A_grid)



[(0, 0)]
[(0, 0), (0, 0), (1, 1), (2, 2)]
[(0, 0), (0, 0), (1, 1), (2, 2)]
[[[0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]]

 [[0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]]

 [[0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]]

 [[0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]]

 [[1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]
  [3 3 3 3 4 4 5 5]
  [3 3 3 3 4 4 5 5]]

 [[1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 

In [26]:
import numpy as np

n=300


A1 = np.linspace(0,10,n)
A2 = np.linspace(0,10,n)
A3 = np.linspace(0,10,n)
A4 = np.linspace(0,100,n)
A5 = np.linspace(0,100,n)
A6 = np.linspace(0,100,n)

A1_grid, A2_grid, A3_grid= np.meshgrid(A1,A2,A3,indexing='ij')
A4_grid, A5_grid, A6_grid= np.meshgrid(A4,A5,A6,indexing='ij')


A_grid1 = A1_grid + A2_grid + A3_grid
A_grid2 = A4_grid + A5_grid + A6_grid



#print(A_grid1)
#print(A_grid2)

max = 0
for i in range(n):
    for j in range(n):
        for l in range(n):
            if A_grid2[i,j,l] > 50 and A_grid1[i,j,l] > max:
                max =  A_grid1[i,j,l]
                
print(max)

30.0


In [1]:
import numpy as np
import itertools
from tqdm import tqdm
import time



n = 500

A1 = np.random.uniform(1,20,size=n)
A2 = np.linspace(0,10,n)
A3 = np.linspace(0,10,n)
"""
start = time.time()

A1_grid, A2_grid, A3_grid = np.meshgrid(A1,A2,A3,indexing='ij')
A=A1_grid+A2_grid+A3_grid
print(np.max(A))

end = time.time()-start

print(f'{end:3.f} seconds')
"""
iterator = itertools.combinations(A1, 3)

high = 0
time_list = list()

for k in range(10):

        start = time.time()

        iterator = itertools.combinations(A1, 3)
        for j,i in enumerate(iterator):
                test1 = i[0]/i[1]+i[2]
                test2 = i[0]*i[1]*i[2]
        if test2 < 20:
                if test1 > high:
                        high = test1
                        high_i = i
        """if j%100000 == 0:
                part = time.time()-start
                print(f'Iteratrion: {j} after {part:.2f} seconds')
        """
        end = time.time()-start
        time_list.append(end)

avg = sum(time_list)/len(time_list)
print(f'{avg:.3f} seconds')

#print(f'{end:.3f} seconds, highest value is {high:.3f} with i: {high_i}')

15.253 seconds
