In [18]:
import numpy as np

n=3

A1 = [(0,0)]
print(A1)
for i in range(n):
    my_tuple = (i,i)
    A1.append(my_tuple)
print(A1)

A2 = A1.copy()
A3 = A1.copy()

print(A3)




A1_grid, A2_grid, A3_grid= np.meshgrid(A1,A2,A3,indexing='ij')

A_grid = A1_grid + A2_grid + A3_grid

#print(A1_grid)
#print(A2_grid)
#print(A3_grid)
print(A_grid)



[(0, 0)]
[(0, 0), (0, 0), (1, 1), (2, 2)]
[(0, 0), (0, 0), (1, 1), (2, 2)]
[[[0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]]

 [[0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]]

 [[0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]]

 [[0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [0 0 0 0 1 1 2 2]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]]

 [[1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 4 4]
  [3 3 3 3 4 4 5 5]
  [3 3 3 3 4 4 5 5]]

 [[1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [1 1 1 1 2 2 3 3]
  [2 2 2 2 3 3 4 4]
  [2 2 2 2 3 3 

In [26]:
import numpy as np

n=300


A1 = np.linspace(0,10,n)
A2 = np.linspace(0,10,n)
A3 = np.linspace(0,10,n)
A4 = np.linspace(0,100,n)
A5 = np.linspace(0,100,n)
A6 = np.linspace(0,100,n)

A1_grid, A2_grid, A3_grid= np.meshgrid(A1,A2,A3,indexing='ij')
A4_grid, A5_grid, A6_grid= np.meshgrid(A4,A5,A6,indexing='ij')


A_grid1 = A1_grid + A2_grid + A3_grid
A_grid2 = A4_grid + A5_grid + A6_grid



#print(A_grid1)
#print(A_grid2)

max = 0
for i in range(n):
    for j in range(n):
        for l in range(n):
            if A_grid2[i,j,l] > 50 and A_grid1[i,j,l] > max:
                max =  A_grid1[i,j,l]
                
print(max)

30.0


In [1]:
weight_genre = 5 # Between 0-5
weight_decade = 5 # Between 0-5
weight_rating = 5 # Between 0-5

weight_genre0 = 5 # Between 0-5
weight_genre1 = 5 # Between 0-5
weight_genre2 = 5 # Between 0-5
weight_genre3 = 5 # Between 0-5
weight_genre4 = 5 # Between 0-5

alpha = weight_genre/(weight_genre+weight_decade+weight_rating)
beta = weight_decade/(weight_genre+weight_decade+weight_rating)
gamma = weight_rating/(weight_genre+weight_decade+weight_rating)

alpha0 = weight_genre0/(weight_genre0+weight_genre1+weight_genre2+weight_genre3+weight_genre4)
alpha1 = weight_genre1/(weight_genre0+weight_genre1+weight_genre2+weight_genre3+weight_genre4)
alpha2 = weight_genre2/(weight_genre0+weight_genre1+weight_genre2+weight_genre3+weight_genre4)
alpha3 = weight_genre3/(weight_genre0+weight_genre1+weight_genre2+weight_genre3+weight_genre4)
alpha4 = weight_genre4/(weight_genre0+weight_genre1+weight_genre2+weight_genre3+weight_genre4)




def u(genre,decade,rating):
    return u = alpha*(alpha0*genre[0]+alpha1*genre[1]+alpha2*genre[2]+alpha3*genre[3]+alpha4*genre[4])+beta*(0.5*decade[0]+decade[1]+0.5*decade[2])+gamma*rating




15.253 seconds
